#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar
# If all your bars have ipc enabled, you can also use 
# polybar-msg cmd quit

# Launch bar1 and bar2
echo "---" | tee -a /tmp/polybar-{left,middle,right}.log
polybar left   >> /tmp/polybar-left.log 2>&1 &
#polybar middle >> /tmp/polybar-middle.log 2>&1 &
polybar right  >> /tmp/polybar-right.log 2>&1 &

echo "Bars launched..."
